package player;

import ooga.cards.Card;

import java.util.List;

/**
 *This interface contains player information(manual and computer players):
 * player name
 * player's hand
 * the card a player chooses to play
 *
 */
public interface player {

    /**
     * returns a list of the player's hand
     * @return
     */
    List<Card> hand();

    /**
     * for AI player, computes the best card of play
     * for manual player, obtains the choice of card from player(ie button click)
     * @param  list of the player's hand
     * @return the chosen card of play
     */
    Card cardBeingPlayed(List<Card> hand, Card card);

    /**
     *for AI player, autogenerated
     * for manual player, string input
     * @return the player's chosen name
     */
    List playerName();

    /**
     *governs what card a player can play
     * @return
     */
    Card playcard(List<Card> hand, Card card);

}
