package ooga.player;

import ooga.cards.Card;
import ooga.piles.DrawPile;
import ooga.piles.Hand;

import java.util.List;

/**
 *This interface contains player information(manual and computer players):
 * player name
 * player's hand
 * the card a player chooses to play
 *
 */
public interface Playeryrdeujhfgk {
    int numcardsperhand = 7;


        /**
         * returns a list of the player's hand
         * @return
         */
        default Hand hand(){
            return playerhand;
        }

        /**
         * for AI player, computes the best card of play
         * for manual player, obtains the choice of card from player(ie button click)
         * @param   hand,card
         * @return the chosen card of play
         */
        Card cardBeingPlayed(List<Card> hand, Card card){

        }

        /**
         *for AI player, autogenerated
         * for manual player, string input
         * @return the player's chosen name
         */
        abstract String playerName(){

        }

        /**
         *governs what card a player can play
         * @return
         */
        Card playcard(List<Card> hand, Card card){

        }


        default void takecard(Card card){
            playerhand.addCard(card);
        }



}
