package ooga.player;

import ooga.cards.Card;

import ooga.piles.Hand;

import java.util.List;


public abstract class Player {
    private Hand playerhand = new Hand();
    private int Id;

    public Player(){
    }

    /**
     * returns a list of the player's hand
     *
     * @return
     */
    public Hand hand() {
        return playerhand;
    }




    /**
     * for manual player, string input
     * @return the player's chosen name
     */
    abstract String manualplayerName();




    /**
     *for AI player, autogenerated
     *
     * @return the player's chosen name
     */
    abstract List AIplayerName(int numaiplayers);



    /**
     *governs what card a player can play
     * @return
     */
    public void removecard(Card handcard) {
        playerhand.removeCard(handcard);
    }


    public void takecard(Card card){
        playerhand.addCard(card);
    }


    public void setID(int Id){
        this.Id = Id;
    }

    public int getID(){
        return Id;
    }


}

